FitnesSkopjeWebApp/FitnesSkopjeWebApp/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FitnesSkopjeWebApp.Models
{
    public class User
    {

        [Key]
        public int id { get; set; }

        [Display(Name = "Име")]
        public string firstName { get; set; }

        [Display(Name = "Презиме")]
        public string lastName { get; set; }

        [Display(Name = "Е-маил")]
        [EmailAddress]
        public string email { get; set; }

        [Display(Name = "Адреса")]
        public string address { get; set; }

        [Display(Name = "Телефонски број")]
        public string phoneNumber { get; set; }
        public string roleId { get; set; } 

        [Display(Name = "Корисничко име")]
        public string username { get; set; }
    }
}

FitnesSkopjeWebApp/FitnesSkopjeWebApp/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FitnesSkopjeWebApp.Models;

namespace FitnesSkopjeWebApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Users
        public ActionResult Index()
        {
            return View(db.AppUsers.ToList());
        }

        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.AppUsers.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,firstName,lastName,email,phoneNumber,roleId")] User user)
        {
            if (ModelState.IsValid)
            {
                db.AppUsers.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.AppUsers.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,firstName,lastName,email,phoneNumber,roleId")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.AppUsers.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.AppUsers.Find(id);
            db.AppUsers.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FitnesSkopjeWebApp/FitnesSkopjeWebApp/Views/Users/Create.cshtml
@model FitnesSkopjeWebApp.Models.User

@{
    ViewBag.Title = "Create";
}

<br />
<br />
<h2>Креирај нов корисник</h2>
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal table-container">
        <br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.firstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.firstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.roleId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.roleId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.roleId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Креирај" class="btn btn-default" />
            </div>
        </div>
        <br />
    </div>
}

<br />
<div>
    <a href="@Url.Action("Index","Users")" class="btn btn-primary right-float">Назад</a>
</div>
<br />
<br />

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FitnesSkopjeWebApp/FitnesSkopjeWebApp/Views/Users/Delete.cshtml
@model FitnesSkopjeWebApp.Models.User

@{
    ViewBag.Title = "Delete";
}

<br />
<br />
<h2>Избриши корисник</h2>
<hr />

<div>

    <dl class="dl-horizontal table-container">
        <h3 style="padding-top: 3%; margin-left: 4%">Дали сте сигурни дека сакате да го избришете овoj корисник?</h3>
        <dt>
            @Html.DisplayNameFor(model => model.firstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phoneNumber)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.roleId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.roleId)
        </dd>*@
        <br />
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <a href="@Url.Action("Index","Users")" class="btn btn-danger" style="margin-left: 15%">Избриши</a>
        }
        <br />
    </dl>
</div>

<div>
    <a href="@Url.Action("Index","Users")" class="btn btn-primary right-float">Назад</a>
</div>
<br />
<br />

FitnesSkopjeWebApp/FitnesSkopjeWebApp/Views/Users/Details.cshtml
@model FitnesSkopjeWebApp.Models.User

@{
    ViewBag.Title = "Details";
}
<br />
<br />
<h2>Детали</h2>
<hr />
<div>
    <dl class="dl-horizontal table-container">
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.firstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phoneNumber)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.roleId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.roleId)
        </dd>*@
        <br />
        <a href="@Url.Action("Edit","Users", new { id = Model.id })" class="btn btn-default" style="margin-left: 15%">Измени</a>
        <br />
        <br />
    </dl>
</div>

<div>
    <a href="@Url.Action("Index","Users")" class="btn btn-primary right-float">Назад</a>
</div>
<br />
<br />

FitnesSkopjeWebApp/FitnesSkopjeWebApp/Views/Users/Edit.cshtml
@model FitnesSkopjeWebApp.Models.User

@{
    ViewBag.Title = "Edit";
}
<br />
<br />
<h2>Промени информации за корисник</h2>

<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal table-container">

        <br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.firstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.firstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.roleId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.roleId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.roleId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Зачувај" class="btn btn-default" />
            </div>
        </div>
        <br />
    </div>
}

<br />
<div>
    <a href="@Url.Action("Index","Users")" class="btn btn-primary right-float">Назад</a>
</div>
<br />
<br />

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FitnesSkopjeWebApp/FitnesSkopjeWebApp/Views/Users/Index.cshtml
@model IEnumerable<FitnesSkopjeWebApp.Models.User>

@{
    ViewBag.Title = "Index";
}
<br />
<br />
<h2>Сите корисници</h2>

<hr />
<a class="btn btn-pink" href="@Url.Action("Create","Users")">Додади нов корисник</a>
<br />
<br />
<div class="table-container">
    <div style="width: 167%">
        <table class="table" style="text-align: center">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayName("Име")
                    </th>
                    <th>
                        @Html.DisplayName("Презиме")
                    </th>
                    <th>
                        @Html.DisplayName("Е-маил")
                    </th>
                    <th>
                        @Html.DisplayName("Телефонски број")
                    </th>
                                 
                    <th>
                        @Html.DisplayName("Опции")
                    </th>
                </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.firstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.lastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.phoneNumber)
                    </td>
                <td>
                    <a href="@Url.Action("Edit", "Users", new { id = item.id })" style="margin-right:5px">
                        <img width="20" height="20" src="@Url.Content("~/Images/edit.png")" title="Измени" />
                    </a>
                    <a href="@Url.Action("Details", "Users", new { id = item.id })" style="margin-right:5px">
                        <img width="20" height="20" src="@Url.Content("~/Images/details.png")" title="Детали" />
                    </a>
                    <a href="@Url.Action("Delete", "Users", new { id = item.id })">
                        <img width="20" height="20" src="@Url.Content("~/Images/delete.png")" title="Избриши" />
                    </a>
                </td>
                </tr>
            }
        </table>
    </div>
</div>