FitnesSkopjeWebApp/FitnesSkopjeWebApp/Models/Gym.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FitnesSkopjeWebApp.Models
{
    public class Gym
    {
        [Key]

        public int Id { get; set; }

        [Display(Name="Теретана")]
        public string Name { get; set; }

        [Display(Name = "Адреса")]
        public string Address { get; set; }

        [Display(Name = "Телефонски број")]
        public string Number { get; set; }

        [Display(Name = "Дејности")]
        public string Areas { get; set; }

        public double? Latitude { get; set; }

        public double? Longitude { get; set; }

        [Display(Name = "Работно време недела")]
        public string workingTimeSunday { get; set; }

        [Display(Name = "Работно време пон-сабота")]
        public string workingTimeWeek { get; set; }
    }
}

FitnesSkopjeWebApp/FitnesSkopjeWebApp/Models/GymTypes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FitnesSkopjeWebApp.Models
{
    public class GymTypes
    {
        [Key]
        public int Id { get; set; }
        public string Type { get; set; }
    }
}

FitnesSkopjeWebApp/FitnesSkopjeWebApp/Controllers/GymsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FitnesSkopjeWebApp.Models;
using FitnesSkopjeWebApp.ViewModels;
using PagedList;

namespace FitnesSkopjeWebApp.Controllers
{
    [Authorize(Roles = "Admin,User")]
    public class GymsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();


        // GET: Gyms
        public ActionResult Index()
        {
            var userEmail = User.Identity.Name;
            if (db.AppUsers.Where(t => t.email == userEmail).FirstOrDefault() != null)
            {
                ViewBag.userId = db.AppUsers.Where(t => t.email == userEmail).FirstOrDefault().id;
            };

            ViewBag.gymTypes = db.Gym_Types.ToList();
            SearchApplicationModels search = new SearchApplicationModels();
            var gyms = GetApplicationsSearch(search).ToList();
            return View((gyms, db.Favourites.ToList(), search));
        }

        [HttpPost]
        public ActionResult Index(SearchApplicationModels search)
        {
            var gymTypeId = Request.Form["checkboxListItem"];
            var lstApps = new List<Gym>();
           
            if (gymTypeId != null)
            {

                var gymTypeName = db.Gym_Types.Find(int.Parse(gymTypeId)).Type;

                lstApps = GetApplicationsSearch(search).Where(a => a.Areas.Contains(gymTypeName)).ToList();

                var userEmail = User.Identity.Name;
                if (db.AppUsers.Where(t => t.email == userEmail).FirstOrDefault() != null)
                {
                    ViewBag.userId = db.AppUsers.Where(t => t.email == userEmail).FirstOrDefault().id;
                };
                ViewBag.gymTypes = db.Gym_Types.ToList();
                ViewBag.SelectedCheckboxItem = int.Parse(gymTypeId);
            }
            else
            {
                lstApps = GetApplicationsSearch(search).ToList();

                var userEmail = User.Identity.Name;
                if (db.AppUsers.Where(t => t.email == userEmail).FirstOrDefault() != null)
                {
                    ViewBag.userId = db.AppUsers.Where(t => t.email == userEmail).FirstOrDefault().id;
                };
                ViewBag.gymTypes = db.Gym_Types.ToList();

            }
            return View((lstApps, db.Favourites.ToList(), search));
        }

        public JsonResult GetGyms(string term)
        {
            List<String> gyms;

            gyms = db.Gyms.Where(x => x.Name.Contains(term)).Select(y => y.Name).ToList();

            return Json(gyms, JsonRequestBehavior.AllowGet);
        }

        // GET: Gyms/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gym gym = db.Gyms.Find(id);
            if (gym == null)
            {
                return HttpNotFound();
            }

            ViewBag.GymName = db.Gyms.Find(id).Name;

            var userEmail = User.Identity.Name;
            var userId = db.AppUsers.Where(t => t.email == userEmail).FirstOrDefault().id;
            var isReviewed = db.Reviews.Where(a => a.gymId == id && a.userId == userId).FirstOrDefault();
            ViewBag.IsReviewed = isReviewed;
            if (isReviewed != null)
            {
                ViewBag.gymReview = isReviewed.id;
            }
            return View((gym, GetReviews(id), IsGymOpened(id)));
        }

        // GET: Gyms/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Gyms/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Address,Number,WorkingTime,Areas")] Gym gym)
        {
            if (ModelState.IsValid)
            {
                db.Gyms.Add(gym);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(gym);
        }

        // GET: Gyms/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gym gym = db.Gyms.Find(id);
            if (gym == null)
            {
                return HttpNotFound();
            }
            return View(gym);
        }

        // POST: Gyms/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Address,Number,WorkingTime,Areas")] Gym gym)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gym).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gym);
        }

        // GET: Gyms/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gym gym = db.Gyms.Find(id);
            if (gym == null)
            {
                return HttpNotFound();
            }
            return View(gym);
        }

        // POST: Gyms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Gym gym = db.Gyms.Find(id);
            db.Gyms.Remove(gym);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IQueryable<Gym> GetGyms()
        {
            return db.Gyms;
        }

        public IQueryable<Gym> GetApplicationsSearch(SearchApplicationModels search)
        {
            var projectIQ = GetGyms();

            if (search.GymId > 0)
                projectIQ = projectIQ.Where(t => t.Id == search.GymId);

            if (search.SearchText != null && search.SearchText?.Trim() != "")
                projectIQ = projectIQ.Where(t => t.Name.Contains(search.SearchText) || t.Areas.Contains(search.SearchText) || t.Address.Contains(search.SearchText));

            return projectIQ;
        }
        public List<Review> GetReviews(int? id)
        {
            if (id != null)
            {
                int gymId = (int)id;
                return db.Reviews
                .Where(r => r.gymId.Equals(gymId))
                .ToList();
            }

            return null;
        }

        public String IsGymOpened(int? id)
        {
            if (id == null)
            {
                throw new Exception("Null gym id");
            }

            var gymId = (int)id;
            var today = DateTime.Now.DayOfWeek;
            var working_time = " ";

            if (today == DayOfWeek.Sunday)
            {
                working_time = db.Gyms.Where(gym => gym.Id.Equals(gymId)).First().workingTimeSunday;

            }
            else
            {
                working_time = db.Gyms.Where(gym => gym.Id.Equals(gymId)).First().workingTimeWeek;

            }
            return CheckTime(working_time);

        }


        public String CheckTime(string working_time)
        {
            if (working_time.Equals(""))
            {
                return "Теретаната не е отворена!";
            }
          
            var parts = working_time.Split('-');

          
            int openingHour = Int32.Parse(parts[0].Split(':')[0]);

            int closingHour = Int32.Parse(parts[1].Split(':')[0]);

            var currentHour = DateTime.Now.Hour;

            if (currentHour >= openingHour &&
                currentHour <= closingHour)
            {
                return "Теретаната е отворена!";
            }
            else
                return "Теретаната не е отворена!";

        }

      
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FitnesSkopjeWebApp/FitnesSkopjeWebApp/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FitnesSkopjeWebApp.Models;

namespace FitnesSkopjeWebApp.Controllers
{
    [Authorize(Roles = "Admin,User")]
    public class ReviewsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Authorize]
        public ActionResult apiReviews()
        {
            return View();
        }


        // GET: Reviews/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Reviews.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }

        // GET: Reviews/Create
        public ActionResult Create(int id)
        {
            ViewBag.GymId = id;
            return View();
        }

      

        // GET: Reviews/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Reviews.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }

     

        // GET: Reviews/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Reviews.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }

      

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FitnesSkopjeWebApp/FitnesSkopjeWebApp/Controllers/api/FavouritesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using System.Web.Mvc;
using FitnesSkopjeWebApp.Models;

namespace FitnesSkopjeWebApp.Controllers.api
{
    public class FavouritesController : ApiController
    {
        private ApplicationDbContext db = new ApplicationDbContext();


        // GET: api/Favourites
        public IQueryable<Favourite> GetFavourites()
        {
            string curentUserEmail = User.Identity.Name;
            var id = db.AppUsers.Where(t => t.email == curentUserEmail).FirstOrDefault().id;
           
            return db.Favourites.Where(u => u.userId == id);
        }


        // POST: api/Favourites
        [ResponseType(typeof(Favourite))]
        public IHttpActionResult PostFavourite(Favourite favourite)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.Favourites.Add(favourite);
            db.SaveChanges();

            return CreatedAtRoute("DefaultApi", new { id = favourite.id }, favourite);
        }

        // DELETE: api/Favourites/5
        [ResponseType(typeof(Favourite))]
        public IHttpActionResult DeleteFavourite(int id)
        {
            Favourite favourite = db.Favourites.Find(id);
            if (favourite == null)
            {
                return NotFound();
            }

            db.Favourites.Remove(favourite);
            db.SaveChanges();

            return Ok(favourite);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

FitnesSkopjeWebApp/FitnesSkopjeWebApp/Views/Gyms/Details.cshtml
@model(FitnesSkopjeWebApp.Models.Gym gym, List<FitnesSkopjeWebApp.Models.Review> reviews, String isOpened)

@{
    ViewBag.Title = "Details";
}
<br />
<br />
<h2>@ViewBag.GymName</h2>

<link href="~/Content/Style.css" rel="stylesheet" />

<div onload="distance()">
    <hr />
    <dl class="dl-horizontal" id="details">
        <div id="detailsLeft">
        <dt>
            @Html.DisplayNameFor(model => model.gym.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gym.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gym.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gym.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gym.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gym.Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gym.workingTimeWeek)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gym.workingTimeWeek)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.gym.workingTimeSunday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gym.workingTimeSunday)
        </dd>
        <dt>
            Растојание
        </dt>
        <dd id="showDist">

        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.gym.Areas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gym.Areas)
        </dd>
        <dt>
            @*-*@
        </dt>
        <dd>
            @if (Model.isOpened.Length == 22)
            {
                <p class="isOpen" style="color:forestgreen">@Model.isOpened </p>
            }
            else
            {
                <p class="isOpen" style="color:orangered"> @Model.isOpened </p>
            }

        </dd>
</div>

<dd>
    <div id="map" style="width: 300px; height: 300px;"></div>
</dd>
        </dl>


<p>
    @if (ViewBag.IsReviewed == null)
    {
        <a class="btn btn-primary" href="@Url.Action("Create","Reviews",new { id=Model.gym.Id})">Додади преглед</a>
    }
    @if (ViewBag.IsReviewed != null)
    {
        <a class="btn btn-primary" href="@Url.Action("Edit","Reviews",new { id=ViewBag.gymReview })">Промени постоечки преглед</a>
    }
</p>

<div class="table-container" id="tableRevDetails">

    @if (Model.reviews.Count() > 0)
    {

        <table class="table" style="text-align:center">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.reviews.First().user.username)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.gym.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.reviews.First().rating)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.reviews.First().comment)
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.reviews)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.user.username)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.gym.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.rating)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.comment)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>
<br />
@if (User.IsInRole("Admin"))
{
<p class="right-float">
    <a href="@Url.Action("Edit","Gyms", new { id = Model.gym.Id })" class="btn btn-pink">Промени</a>
    <a href="@Url.Action("Index","Gyms")" class="btn btn-primary">Назад</a>
</p>
}
<br /><br />


@section Scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <link rel="shortcut icon" type="image/x-icon" href="docs/images/favicon.ico" />

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==" crossorigin="" />
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js" integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA==" crossorigin=""></script>

    <script>
    /*Pocetok za mapa*/
    var latitude =@Model.gym.Latitude;
    var longitute =@Model.gym.Longitude;
    var map = L.map('map').setView([latitude, longitute], 16);

    var tiles = L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
        maxZoom: 18,
        attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, ' +
            'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
        id: 'mapbox/streets-v11',
        tileSize: 512,
        zoomOffset: -1
    }).addTo(map);

        var marker = L.marker([41.990900, 21.439920]).addTo(map)
            .bindPopup('<b>@Model.gym.Name</b><br />').openPopup();

    var circle = L.circle([41.990900, 21.439920], {
        color: '#4F729D',
        fillColor: '#247DCA',
        fillOpacity: 0.5,
        radius: 50
    }).addTo(map);

        function blink_text() {
            $('.isOpen').fadeOut(500);
            $('.isOpen').fadeIn(500);
        }
        setInterval(blink_text, 1000);

    function onMapClick(e) {
        popup
            .setLatLng(e.latlng)
            .setContent('You clicked the map at ' + e.latlng.toString())
            .openOn(map);
    }

        map.on('click', onMapClick);
        /*Kraj za mapa*/

        /*Pocetok za distance*/
        function distance(lon1, lat1, lon2, lat2) {
            var R = 6371; 
            var dLat = (lat2 - lat1).toRad();  
            var dLon = (lon2 - lon1).toRad();
            var a = Math.sin(dLat / 2) * Math.sin(dLat / 2) +
                Math.cos(lat1.toRad()) * Math.cos(lat2.toRad()) *
                Math.sin(dLon / 2) * Math.sin(dLon / 2);
            var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
            var d = R * c; 
            return d;
        }

        /** Converts numeric degrees to radians */
        if (typeof (Number.prototype.toRad) === "undefined") {
            Number.prototype.toRad = function () {
                return this * Math.PI / 180;
            }
        }

        window.navigator.geolocation.getCurrentPosition(function (pos) {
            console.log(pos);
            console.log(
                distance(pos.coords.longitude, pos.coords.latitude, @Model.gym.Longitude, @Model.gym.Latitude)
            );
            document.getElementById("showDist").innerHTML = "≈" + distance(pos.coords.longitude, pos.coords.latitude, @Model.gym.Longitude, @Model.gym.Latitude).toFixed(2) + " км";
        });
        /*Kraj za distance*/

    </script>
}

FitnesSkopjeWebApp/FitnesSkopjeWebApp/Views/Gyms/Index.cshtml
@model (List<FitnesSkopjeWebApp.Models.Gym> gyms, List<FitnesSkopjeWebApp.Models.Favourite> favourites, FitnesSkopjeWebApp.ViewModels.SearchApplicationModels search)


@{
    ViewBag.Title = "Index";
}
<link href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />

<style>
    .item {
        cursor: pointer;
    }

    a {
        display: inline;
    }
</style>

<link href="~/Content/Style.css" rel="stylesheet" />


@Html.Partial("~/Views/Search/_SearchApplication.cshtml", Model.search)


@if (Model.gyms.Count > 0)
{


    <div class="row">
        <div class="filtercontainer">
            <div class="header btn btn-primary">
                <div class="filterbutton">Прикажи филтри</div>
            </div>
            <div class="col-sm-4 filtercontent">
                @using (Html.BeginForm("Index", "Gyms", FormMethod.Post, new { id = "checkboxForm" }))
                {
                    @Html.AntiForgeryToken()
                    <h4 style="margin-left: 8%; font-size: 150%">Филтер по дејности</h4>
                    <ul>
                        @foreach (var item in ViewBag.gymTypes)
                        {
                            if (item.Id == ViewBag.SelectedCheckboxItem)
                            {
                                <li style="list-style:none"><input type="radio" value="@item.Id" name="checkboxListItem" checked /><span style="padding-left:3px">@item.Type</span></li>
                            }
                            else
                            {
                                <li style="list-style:none"><input type="radio" value="@item.Id" name="checkboxListItem" /><span style="padding-left:3px">@item.Type</span></li>
                            }
                        }
                    </ul>
                    <input style="margin-left: 8%" type="submit" class="btn btn-pink clearsearch mr10" value="Избриши филтри" />
                    <br /><label style="display: none"></label>
                }
            </div>
        </div>
        <div class="col-sm-12">
            <br />
            <br />
            <div class="table-container">
                <table id="gyms" class="table" style="text-align: center">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.gyms.First().Name)
                            </th>
                            <th>
                                Локација
                            </th>
                            @if (User.IsInRole("User"))
                            {
                                <th>
                                    Додај во омилени
                                </th>
                            }
                            @if (User.IsInRole("Admin"))
                            {
                                <th>
                                    Акции
                                </th>
                            }
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model.gyms)
                        {
                            <tr onclick="Redirect(@item.Id)">

                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                    <p>Кликни за детали</p>
                                </td>
                                
                                <td id="gymMap">
                                    <div style="text-align:center" class="item" data-gym-latitude="@item.Latitude" data-gym-longitude="@item.Longitude">
                                        Мапа <p>Погледни ја тука</p>
                                        <iframe style="display:none" class="map" width="160" height="160" src="https://maps.google.com/maps?q=@item.Latitude,@item.Longitude&hl=es;z=17&amp;output=embed"></iframe>
                                    </div>

                                </td>

                                @if (User.IsInRole("User"))
                                {
                                    <td style="text-align:center">
                                        @using (Html.BeginForm("Create", "Favourites", FormMethod.Post))
                                        {
                                            @Html.AntiForgeryToken()
                                            <input type="hidden" name="gymId" id="gym_Id" value="@item.Id" />
                                            <input type="hidden" name="gymName" id="gym_Name" value="@item.Name" />

                                            if (Model.favourites.Where(a => a.gymId == item.Id && a.userId == ViewBag.userId).FirstOrDefault() == null)
                                            {
                                                <button type="submit" class="btn btn-link"> <img width="28" height="25" src="@Url.Content("~/Images/empty.png")" /></button>
                                            }
                                            if (Model.favourites.Where(a => a.gymId == item.Id && a.userId == ViewBag.userId).FirstOrDefault() != null)
                                            {
                                                <button type="submit" class="btn btn-link"> <img width="28" height="25" src="@Url.Content("~/Images/full.png")" /></button>
                                            }
                                        }
                                    </td>
                                }
                                @if (User.IsInRole("Admin"))
                                {
                                    <td class="row">
                                        <div class="col-md-4 col-md-offset-2">
                                            <a href="@Url.Action("Edit", "Gyms", new { id = item.Id })">
                                                <img width="20" height="20" src="@Url.Content("~/Images/edit.png")" />
                                            </a>
                                        </div>

                                        <div class="col-md-4">
                                            <a href="@Url.Action("Delete", "Gyms", new { id = item.Id })">
                                                <img width="20" height="20" src="@Url.Content("~/Images/delete.png")" />
                                            </a>
                                        </div>

                                    </td>
                                }
                            </tr>
                        }

                    </tbody>
                    @if (User.IsInRole("Admin"))
                    {
                        <tfoot>
                            <tr>
                                <td></td>
                                <td></td>
                                <td class="row">
                                    <a class="btn btn-primary right-float" href="@Url.Action("Create","Gyms")">Додади нова</a>
                                </td>
                            </tr>

                        </tfoot>
                    }
                    </table>
            </div>
        </div>
    </div>
}
else
{
    <p>Не постои теретана со избраните параметри!S</p>
}

@section Scripts{
    <script src="~/Scripts/pagination.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {

            $(".header").click(function () {


                $header = $(this);
                
                $filtercontent = $header.next();
                
                $filtercontent.slideToggle(500, function () {
                    
                    $header.text(function () {
                        
                        return $filtercontent.is(":visible") ? "Затвори филтри" : "Прикажи филтри";
                    });
                });

            });

            $(".item").mouseover(function () {
                $(this).children(".map").show();
            }).mouseout(function () {
                $(this).children(".map").hide();
            });


            $("#gyms").DataTable({
                pageLength: 5,
                lengthMenu: [[5, 10, 20, -1], [5, 10, 20, 'All']],
                "paging": true,
                "ordering": false,
                "info": false,
                "searching": false,
                "bLengthChange": false,
                "pagingType": "full_numbers"
            });


            $("input:radio").on("click", function () {
                if ($(this).is(":checked")) {
                    $("#checkboxForm").submit()
                }
            })

            $("#clearFilterButton").on("click", function () {
                $('input[name="checkboxListItem"]').prop('checked', false);
            })

        });

        function Redirect(itemId) {
            location.pathname = "Gyms/Details/" + itemId
        };
       

        $(function () {
            $(document).tooltip();
        });
    </script>

    <style>
        tbody tr:hover {
            background-color: lightblue;
        }
    </style>

}